// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.21.12
// source: pncp.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	PncpService_Pncp_FullMethodName = "/pncp.PncpService/Pncp"
)

// PncpServiceClient is the client API for PncpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PncpServiceClient interface {
	Pncp(ctx context.Context, in *PncpAvailableLicenseRequest, opts ...grpc.CallOption) (*PncpAvailableLicenseResponse, error)
}

type pncpServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPncpServiceClient(cc grpc.ClientConnInterface) PncpServiceClient {
	return &pncpServiceClient{cc}
}

func (c *pncpServiceClient) Pncp(ctx context.Context, in *PncpAvailableLicenseRequest, opts ...grpc.CallOption) (*PncpAvailableLicenseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PncpAvailableLicenseResponse)
	err := c.cc.Invoke(ctx, PncpService_Pncp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PncpServiceServer is the server API for PncpService service.
// All implementations must embed UnimplementedPncpServiceServer
// for forward compatibility
type PncpServiceServer interface {
	Pncp(context.Context, *PncpAvailableLicenseRequest) (*PncpAvailableLicenseResponse, error)
	mustEmbedUnimplementedPncpServiceServer()
}

// UnimplementedPncpServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPncpServiceServer struct {
}

func (UnimplementedPncpServiceServer) Pncp(context.Context, *PncpAvailableLicenseRequest) (*PncpAvailableLicenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pncp not implemented")
}
func (UnimplementedPncpServiceServer) mustEmbedUnimplementedPncpServiceServer() {}

// UnsafePncpServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PncpServiceServer will
// result in compilation errors.
type UnsafePncpServiceServer interface {
	mustEmbedUnimplementedPncpServiceServer()
}

func RegisterPncpServiceServer(s grpc.ServiceRegistrar, srv PncpServiceServer) {
	s.RegisterService(&PncpService_ServiceDesc, srv)
}

func _PncpService_Pncp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PncpAvailableLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PncpServiceServer).Pncp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PncpService_Pncp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PncpServiceServer).Pncp(ctx, req.(*PncpAvailableLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PncpService_ServiceDesc is the grpc.ServiceDesc for PncpService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PncpService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pncp.PncpService",
	HandlerType: (*PncpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pncp",
			Handler:    _PncpService_Pncp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pncp.proto",
}
